### ISSUE TITLE
Tests are broken on Node 8

### ISSUE THREAD

**Issue by corhere** [lukeapage/pngjs#104]
Tested on 32d0580

```
$ node --version
v8.10.0

$ yarn test
[...snip...]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: There are some read requests waiting on finished stream
    at module.exports.ChunkStream._end (/[...]/pngjs/lib/chunkstream.js:100:7)
    at module.exports.ChunkStream.end (/[...]/pngjs/lib/chunkstream.js:86:10)
    at emitNone (events.js:111:20)
    at Inflate.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


  337 tests
  403 passed

  Pass!
Tests available at http://localhost:8000/
Comparing in PhantomJS
Comparison Test Results:
Success: [...snip...]
Failure: z09n2c08, z06n2c08, z03n2c08, z00n2c08
```

**Comment by lukeapage** [comment]
I believe this is fixed.
