### ISSUE TITLE
Error: Unexpected end of input Emitted 'error' event crashes nodejs

### ISSUE THREAD

**Issue by coranos** [lukeapage/pngjs#127]
npmjs will occasionally hard-crash node by emitting an error.

this seems like extreme overkill, as the error should simply be thrown (to be caught and logged) instead of emitted.

Error: Unexpected end of input
    at module.exports.ChunkStream._end (node_modules/pngjs/lib/chunkstream.js:100:7)
    at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:203:12)
    at module.exports.ChunkStream.end (node_modules/pngjs/lib/chunkstream.js:90:10)
    at module.exports.ParserAsync._finished (node_modules/pngjs/lib/parser-async.js:143:8)
    at module.exports.Parser._parseIEND (node_modules/pngjs/lib/parser.js:295:10)
    at module.exports.ChunkStream._processRead (node_modules/pngjs/lib/chunkstream.js:174:13)
    at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:193:14)
    at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
    at exports.PNG.PNG.write (node_modules/pngjs/lib/png.js:93:16)
    at ReadStream.ondata (_stream_readable.js:696:20)
Emitted 'error' event at:
    at module.exports.emit (events.js:197:13)
    at module.exports.ChunkStream._process (node_modules/pngjs/lib/chunkstream.js:207:10)
    at module.exports.ChunkStream.write (node_modules/pngjs/lib/chunkstream.js:61:8)
    at exports.PNG.PNG.write (node_modules/pngjs/lib/png.js:93:16)
    at ReadStream.ondata (_stream_readable.js:696:20)
    at ReadStream.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
    at fs.read (internal/fs/streams.js:183:12)

**Comment by lukeapage** [comment]
Prs welcome. Please include a link to some solid documentation on best practices.

**Comment by coranos** [comment]
Ok looks like this is an error in someone else's code.

Here you trap the try/catch and instead emit the error:
https://github.com/lukeapage/pngjs/blob/master/lib/chunkstream.js#L207

which they then have to listen for, and reject the promise:
https://github.com/danielbarela/node-pureimage/blob/master/src/pureimage.js#L90

I'll submit the PR there. 
I don't know what best practice is for error handling, but your unit tests show his code is wrong and yours is right.

**Comment by mrtrandinhvn** [comment]
For anyone stumble to this issue using puppeteer and backstopjs, I have to run puppeteer in headful mode to avoid this exception.
