### ISSUE TITLE
Error - ChunkStream incorrectly closed when input chunk boundary crosses fileCrc

### ISSUE THREAD

**Issue by smallnamespace** [lukeapage/pngjs#129]
If an input stream's final chunk boundary happens to line up in the middle of the 4-byte `fileCrc`, then you get this trace:

```
Error: Unexpected end of input
    at module.exports.ChunkStream._end (/pngjs/lib/chunkstream.js:100:7)
    at module.exports.ChunkStream._process (/pngjs/lib/chunkstream.js:203:12)
    at module.exports.ChunkStream.end (/pngjs/lib/chunkstream.js:90:10)
    at module.exports.ParserAsync._finished (/pngjs/lib/parser-async.js:143:8)
    at module.exports.Parser._parseIEND (/pngjs/lib/parser.js:295:10)
    at module.exports.ChunkStream._processRead (/pngjs/lib/chunkstream.js:174:13)
    at module.exports.ChunkStream._process (/pngjs/lib/chunkstream.js:193:14)
    at module.exports.ChunkStream.write (/pngjs/lib/chunkstream.js:61:8)
    at exports.PNG.PNG.write (/pngjs/lib/png.js:93:16)
    at ReadStream.ondata (_stream_readable.js:696:22)
Emitted 'error' event at:
    at module.exports.emit (events.js:196:13)
    at module.exports.ChunkStream._process (/pngjs/lib/chunkstream.js:207:10)
    at module.exports.ChunkStream.write (/pngjs/lib/chunkstream.js:61:8)
    at exports.PNG.PNG.write (/pngjs/lib/png.js:93:16)
    at ReadStream.ondata (_stream_readable.js:696:22)
    at ReadStream.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at ReadStream.Readable.push (_stream_readable.js:226:10)
    at internal/fs/streams.js:185:12
```

This is because `destroySoon` is called at https://github.com/lukeapage/pngjs/blob/master/lib/parser-async.js#L143 when `IEND` is parsed, which causes `end` processing to happen prematurely, before the final bytes were `write`-en from the read stream.

To reproduce, just set `highWaterMark` to low level, e.g.:
```
fs.createReadStream(path.join(__dirname, "in", "tbbn0g04.png"), { highWaterMark: 2 })
    .pipe(new PNG());
```

**Comment by omar-oslo** [comment]
I get similar error for a corrupted PNG file with following stack trace for version 3.4.0. @smallnamespace Do you know if this is same issue ? I need to test if this PR fixes the error below.

> { Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17)
    at Inflate._processChunk (D:\home\site\wwwroot\node_modules\pngjs\lib\sync-inflate.js:110:28)
    at zlibBufferSync (D:\home\site\wwwroot\node_modules\pngjs\lib\sync-inflate.js:151:17)
    at inflateSync (D:\home\site\wwwroot\node_modules\pngjs\lib\sync-inflate.js:155:10)
    at module.exports (D:\home\site\wwwroot\node_modules\pngjs\lib\parser-sync.js:85:20)
    at Object.exports.read (D:\home\site\wwwroot\node_modules\pngjs\lib\png-sync.js:10:10)
