### ISSUE TITLE
Error: incorrect data check

### ISSUE THREAD

**Issue by tgrajewski** [lukeapage/pngjs#136]
I have somewhat weird PNG file that fails to load in pngjs and some desktop software, but loads fine in other software. Here is how to reproduce the error:

```
> const fs = require('fs');
> const {PNG} = require('pngjs');
> var data = fs.readFileSync('83.png');
> var png = PNG.sync.read(data);
Thrown:
{ Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
    at Inflate._processChunk (...\node_modules\pngjs\lib\sync-inflate.js:110:28)
    at zlibBufferSync (...\node_modules\pngjs\lib\sync-inflate.js:151:17)
    at inflateSync (...\node_modules\pngjs\lib\sync-inflate.js:155:10)
    at module.exports (...\node_modules\pngjs\lib\parser-sync.js:85:20)
    at Object.exports.read (...\node_modules\pngjs\lib\png-sync.js:10:10) errno: -3, code: 'Z_DATA_ERROR' }
```

pngjs v3.4.0, Node v10.16.3 64-bit, Windows 10 64-bit.

The image that triggers the error (white on transparent):
![83](https://user-images.githubusercontent.com/4324821/66333815-0aca9600-e938-11e9-8b58-5e7906f0a88d.png)

**Comment by lukeapage** [comment]
Its a zlib data error as it says - if you want to investigate how node might be able to parse it okay then feel free to do that and send a pr

**Comment by tgrajewski** [comment]
OK, but why this is issue has been closed? The bug still exists, right? Even if the bug is in Zlib and PNGJS uses Zlib, then bug is also in PNGJS for me and for all other users. The ticket should stay open, so other can see it, if they stumble upon it until it's fixed.

**Comment by lukeapage** [comment]
Ok I can re-open it.

**Comment by lukeapage** [comment]
IMO it’s probably not a bug - it’s a feature request to allow parsing non standard zipping that zlib does not support.

**Comment by tgrajewski** [comment]
Or maybe the file is just corrupt. In any case would be great if the error thrown would indicate that it's something wrong with the file, not library.
