### ISSUE TITLE
Error: unexpected end of file

### ISSUE THREAD

**Issue by florianbepunkt** [lukeapage/pngjs#137]
I get a lot of these errors when using this lib

```
(node:73799) UnhandledPromiseRejectionWarning: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:170:17)
    at Inflate._processChunk (/Users/florian/Github Repositories/cm-eurystheus/node_modules/pngjs/lib/sync-inflate.js:110:28)
    at zlibBufferSync (/Users/florian/Github Repositories/cm-eurystheus/node_modules/pngjs/lib/sync-inflate.js:151:17)
    at inflateSync (/Users/florian/Github Repositories/cm-eurystheus/node_modules/pngjs/lib/sync-inflate.js:155:10)
    at module.exports (/Users/florian/Github Repositories/cm-eurystheus/node_modules/pngjs/lib/parser-sync.js:85:20)
    at Object.exports.read (/Users/florian/Github Repositories/cm-eurystheus/node_modules/pngjs/lib/png-sync.js:10:10)
    at Eurystheus.<anonymous> (/Users/florian/Github Repositories/cm-eurystheus/src/index.ts:179:27)
    at Generator.next (<anonymous>)
    at /Users/florian/Github Repositories/cm-eurystheus/src/index.ts:8:71
    at new Promise (<anonymous>)
```

In my code I have this in a lo

```
private async compare(
    testSrc: string,
    refSrc: string
  ): Promise<Buffer | boolean> {
    console.log("Test path", testSrc);
    console.log("Reference path", refSrc);

    const refFile = fs.readFileSync(refSrc);
    const testFile = fs.readFileSync(testSrc);

    const ref = PNG.sync.read(refFile);
    const test = PNG.sync.read(testFile);

    const { width, height } = ref;
    const diff = new PNG({ width, height });

    const match = pixelmatch(ref.data, test.data, diff.data, width, height, {
      alpha: 0.1,
      threshold: 0.1
    });

    const diffBuf = PNG.sync.write(diff);

    return diffBuf;
  }
```

**Comment by florianbepunkt** [comment]
okay, had a race condition. closing this.
