### ISSUE TITLE
Parsing a particular PNG image results in Error: Unexpected end of input

### ISSUE THREAD

**Issue by Zloka** [lukeapage/pngjs#209]
I've used the library to process a large amount of PNG images, and only one image is giving me a headache that I can't figure out.

The stacktrace is:
```
Error: Unexpected end of input
    at module.exports.ChunkStream._end (/Users/zakke/sources/mafy/mafynetti/pdf-microservice/node_modules/pngjs/lib/chunkstream.js:92:24)
    at module.exports.ChunkStream.end (/Users/zakke/sources/mafy/mafynetti/pdf-microservice/node_modules/pngjs/lib/chunkstream.js:81:10)
    at exports.PNG.PNG.end (/Users/zakke/sources/mafy/mafynetti/pdf-microservice/node_modules/pngjs/lib/png.js:100:16)
    at ReadStream.onend (_stream_readable.js:672:10)
    at Object.onceWrapper (events.js:286:20)
    at ReadStream.emit (events.js:203:15)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
The code in the simplest form is:
```
    const png = new PNG();
    fs.createReadStream(filename)
      .pipe(png)
      .on('parsed', () => {
        console.log(`Successfully parsed ${filename}`);
      })
      .on('error', (error) => {
        console.log(error);
        console.error(`Error parsing PNG-file: ${filename}!`);
      });
```

Any idea what could be wrong? 🤔
Here's the PNG-file in question:
![harj1_234-1](https://user-images.githubusercontent.com/17513212/97834612-ed096500-1ce0-11eb-9dc7-cf23facb757d.png)

**Comment by lukeapage** [comment]
Probably the image is corrupt? But other readers are maybe ignoring problems?

The error means that pngjs has asked for more data but the stream has ended - so the file may be missing bytes at the end. It could be the last bytes don’t even alter the image appearance but pngjs doesn’t know that.

**Comment by lukeapage** [comment]
You could debug to work out at what stage it is requesting more data and see why - that should tell you what pngjs thinks is missing and would identify if the image is corrupt or if there is a bug in pngjs.
We could also implement a way to be more resilient on errors but I fear that might be a lot of work (ignore all errors would be easy - ignore consequential errors hard)
