### ISSUE TITLE
Uncaught exception: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by oetr** [lukeapage/pngjs#294]
To reproduce the issue, use the following file and the "sync.js" file in the examples folder:

![crash-66c6d2d2335412cf5e4146e05fa149ca14851c5e](https://user-images.githubusercontent.com/240414/196217165-62f67516-0213-4bc6-9f53-f6b75e387a46.png)

The crash was found using jazzer.js https://github.com/CodeIntelligenceTesting/jazzer.

```$ npx run sync.js ./crash-66c6d2d2335412cf5e4146e05fa149ca14851c5e out.png

Starting: sync.js ./crash-66c6d2d2335412cf5e4146e05fa149ca14851c5e out.png
node:internal/buffer:84
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:387:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readUInt32BE (node:internal/buffer:309:5)
    at module.exports.Parser._parseIHDR (/home/peter/Documents/Programming/JS-Fuzzing/pngjs/lib/parser.js:122:20)
    at module.exports.SyncReader.process (/home/peter/Documents/Programming/JS-Fuzzing/pngjs/lib/sync-reader.js:32:17)
    at module.exports (/home/peter/Documents/Programming/JS-Fuzzing/pngjs/lib/parser-sync.js:68:10)
    at Object.exports.read (/home/peter/Documents/Programming/JS-Fuzzing/pngjs/lib/png-sync.js:7:10)
    at Object.<anonymous> (/home/peter/Documents/Programming/JS-Fuzzing/pngjs/examples/sync.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

**Comment by lukeapage** [comment]
Invalid png files will error..

**Comment by oetr** [comment]
An uncaught exception might be caused by a logical error in the implementation. But feel free to close it, if you think that it's not an issue!

**Comment by lukeapage** [comment]
Yes we don’t check the bounds - we could give a nicer error but it’s not unsafe since node stops us accessing memory that would be a security risk afaik
