### ISSUE TITLE
Cannot run tests from node/npm

### ISSUE THREAD

**Issue by fuchsia** [lukeapage/pngjs#36]
According to your documentation, the tests are run via `node test`. But that fails. (`Error: Cannot find module '...pngjs\test'`)

So I tried `npm test`. I had to manually install the dependencies. The tests then failed with `Error: Cannot find module '...\pngjs\test\run-compare'` and I can't see a way to fix that.

(Appologies if I've done anything stupid.)

System: Windows 7 with Node 5.2 x64.

**Comment by lukeapage** [comment]
I corrected the documentation to say `npm test`. not sure why it doesn't work for you. I'll try a new install..

**Comment by lukeapage** [comment]
tested on windows 10, Node 5.2 x64

1. cloned repo
2. ran `npm i`
3 ran `npm test`

output:
```
$ npm i

> phantomjs@1.9.19 install c:\dev\test\pngjs\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\lpage\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...
  [=====================================---] 93% 0.0s
Received 7292K total.
Extracting zip contents
Removing c:\dev\test\pngjs\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\xxx\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1450185091625\phantomjs-1.9.8-windows -> c:\dev\test\pngjs\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at c:\dev\test\pngjs\node_modules\phantomjs\lib\phantom\phantomjs.exe
pngjs@2.2.0 c:\dev\test\pngjs
├── buffer-equal@0.0.1
├─┬ connect@3.4.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ finalhandler@0.4.0
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ └── unpipe@1.0.0
│ ├── parseurl@1.3.0
│ └── utils-merge@1.0.0
├─┬ eslint@1.10.3
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── has-ansi@2.0.0
│ │ ├── strip-ansi@3.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.5.1
│ │ ├─┬ readable-stream@2.0.4
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── process-nextick-args@1.0.6
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ doctrine@0.7.2
│ │ ├── esutils@1.1.6
│ │ └── isarray@0.0.1
│ ├── escape-string-regexp@1.0.3
│ ├─┬ escope@3.3.0
│ │ ├─┬ es6-map@0.1.3
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.10
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.3
│ │ │ ├── es6-symbol@3.0.2
│ │ │ └── event-emitter@0.3.4
│ │ ├── es6-weak-map@2.0.1
│ │ └─┬ esrecurse@3.1.1
│ │   └── estraverse@3.1.0
│ ├── espree@2.2.5
│ ├── estraverse@4.1.1
│ ├── estraverse-fb@1.3.1
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@1.2.4
│ │ └─┬ flat-cache@1.0.10
│ │   ├─┬ del@2.2.0
│ │   │ ├─┬ globby@4.0.0
│ │   │ │ ├─┬ array-union@1.0.1
│ │   │ │ │ └── array-uniq@1.0.2
│ │   │ │ ├── arrify@1.0.1
│ │   │ │ └── glob@6.0.1
│ │   │ ├── is-path-cwd@1.0.0
│ │   │ ├─┬ is-path-in-cwd@1.0.0
│ │   │ │ └── is-path-inside@1.0.0
│ │   │ ├── pify@2.3.0
│ │   │ └─┬ pinkie-promise@2.0.0
│ │   │   └── pinkie@2.0.1
│ │   ├── read-json-sync@1.1.1
│ │   └── write@0.2.1
│ ├─┬ glob@5.0.15
│ │ └── inflight@1.0.4
│ ├── globals@8.14.0
│ ├─┬ handlebars@4.0.5
│ │ ├── optimist@0.6.1
│ │ ├─┬ source-map@0.4.4
│ │ │ └── amdefine@1.0.0
│ │ └─┬ uglify-js@2.6.1
│ │   ├── async@0.2.10
│ │   ├── source-map@0.5.3
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.10.0
│ │     ├── camelcase@1.2.1
│ │     ├─┬ cliui@2.1.0
│ │     │ ├─┬ center-align@0.1.2
│ │     │ │ ├─┬ align-text@0.1.3
│ │     │ │ │ ├─┬ kind-of@2.0.1
│ │     │ │ │ │ └── is-buffer@1.1.0
│ │     │ │ │ ├── longest@1.0.1
│ │     │ │ │ └── repeat-string@1.5.2
│ │     │ │ └── lazy-cache@0.2.7
│ │     │ ├── right-align@0.1.3
│ │     │ └── wordwrap@0.0.2
│ │     ├── decamelize@1.1.1
│ │     └── window-size@0.1.0
│ ├─┬ inquirer@0.11.0
│ │ ├── ansi-escapes@1.1.0
│ │ ├── ansi-regex@2.0.0
│ │ ├─┬ cli-cursor@1.0.2
│ │ │ └─┬ restore-cursor@1.0.1
│ │ │   ├── exit-hook@1.1.1
│ │ │   └── onetime@1.0.0
│ │ ├── cli-width@1.1.0
│ │ ├── figures@1.4.0
│ │ ├── lodash@3.10.1
│ │ ├─┬ readline2@1.0.1
│ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ ├── is-fullwidth-code-point@1.0.0
│ │ │ └── mute-stream@0.0.5
│ │ ├── run-async@0.1.0
│ │ └── rx-lite@3.1.2
│ ├─┬ is-my-json-valid@2.12.3
│ │ ├── generate-function@2.0.0
│ │ ├─┬ generate-object-property@1.2.0
│ │ │ └── is-property@1.0.2
│ │ ├── jsonpointer@2.0.0
│ │ └── xtend@4.0.1
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.2
│ ├─┬ js-yaml@3.4.5
│ │ ├─┬ argparse@1.0.3
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.1
│ ├─┬ json-stable-stringify@1.0.0
│ │ └── jsonify@0.0.0
│ ├─┬ lodash.clonedeep@3.0.2
│ │ ├─┬ lodash._baseclone@3.3.0
│ │ │ ├── lodash._baseassign@3.2.0
│ │ │ └── lodash._basefor@3.0.2
│ │ └── lodash._bindcallback@3.0.1
│ ├─┬ lodash.merge@3.3.2
│ │ ├── lodash._arraycopy@3.0.0
│ │ ├── lodash._arrayeach@3.0.0
│ │ ├─┬ lodash._createassigner@3.1.1
│ │ │ └── lodash._isiterateecall@3.0.9
│ │ ├── lodash._getnative@3.9.1
│ │ ├── lodash.isarguments@3.0.4
│ │ ├── lodash.isarray@3.0.4
│ │ ├── lodash.isplainobject@3.2.0
│ │ ├── lodash.istypedarray@3.0.2
│ │ ├── lodash.keys@3.1.2
│ │ ├── lodash.keysin@3.0.8
│ │ └─┬ lodash.toplainobject@3.0.0
│ │   └── lodash._basecopy@3.0.1
│ ├─┬ lodash.omit@3.1.0
│ │ ├── lodash._arraymap@3.0.0
│ │ ├─┬ lodash._basedifference@3.0.3
│ │ │ ├── lodash._baseindexof@3.1.0
│ │ │ ├── lodash._cacheindexof@3.0.2
│ │ │ └── lodash._createcache@3.1.2
│ │ ├── lodash._baseflatten@3.1.4
│ │ ├── lodash._pickbyarray@3.0.2
│ │ ├── lodash._pickbycallback@3.0.0
│ │ └── lodash.restparam@3.6.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.2
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── object-assign@4.0.1
│ ├─┬ optionator@0.6.0
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@1.0.7
│ │ ├── levn@0.2.5
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.1
│ │ └── wordwrap@0.0.3
│ ├── path-is-absolute@1.0.0
│ ├── path-is-inside@1.0.1
│ ├── shelljs@0.5.3
│ ├── strip-json-comments@1.0.4
│ ├── text-table@0.2.0
│ ├─┬ user-home@2.0.0
│ │ └── os-homedir@1.0.1
│ └── xml-escape@1.0.0
├─┬ istanbul@0.3.22
│ ├── abbrev@1.0.7
│ ├── async@1.5.0
│ ├─┬ escodegen@1.7.1
│ │ ├── esprima@1.2.5
│ │ ├── estraverse@1.9.3
│ │ ├── optionator@0.5.0
│ │ └── source-map@0.2.0
│ ├── esprima@2.5.0
│ ├─┬ fileset@0.2.1
│ │ └── minimatch@2.0.10
│ ├── nopt@3.0.6
│ ├─┬ once@1.3.3
│ │ └── wrappy@1.0.1
│ ├── resolve@1.1.6
│ ├─┬ supports-color@3.1.2
│ │ └── has-flag@1.0.0
│ ├─┬ which@1.2.0
│ │ └─┬ is-absolute@0.1.7
│ │   └── is-relative@0.1.3
│ └── wordwrap@1.0.0
├─┬ phantomjs@1.9.19
│ ├── adm-zip@0.4.4
│ ├─┬ fs-extra@0.23.1
│ │ ├── graceful-fs@4.1.2
│ │ ├── jsonfile@2.2.3
│ │ └── rimraf@2.4.4
│ ├── kew@0.4.0
│ ├─┬ md5@2.0.0
│ │ ├── charenc@0.0.1
│ │ ├── crypt@0.0.1
│ │ └── is-buffer@1.0.2
│ ├─┬ npmconf@2.1.1
│ │ ├─┬ config-chain@1.1.9
│ │ │ └── proto-list@1.2.4
│ │ ├── ini@1.3.4
│ │ ├─┬ osenv@0.1.3
│ │ │ └── os-tmpdir@1.0.1
│ │ ├── semver@4.3.6
│ │ └── uid-number@0.0.5
│ ├── progress@1.1.8
│ ├─┬ request@2.42.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.4
│ │ │ └── readable-stream@1.0.33
│ │ ├── caseless@0.6.0
│ │ ├── forever-agent@0.5.2
│ │ ├─┬ form-data@0.1.4
│ │ │ ├── async@0.9.2
│ │ │ ├─┬ combined-stream@0.0.7
│ │ │ │ └── delayed-stream@0.0.5
│ │ │ └── mime@1.2.11
│ │ ├─┬ hawk@1.1.1
│ │ │ ├── boom@0.4.2
│ │ │ ├── cryptiles@0.2.2
│ │ │ ├── hoek@0.9.1
│ │ │ └── sntp@0.2.4
│ │ ├─┬ http-signature@0.10.1
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── json-stringify-safe@5.0.1
│ │ ├── mime-types@1.0.2
│ │ ├── node-uuid@1.4.7
│ │ ├── oauth-sign@0.4.0
│ │ ├── qs@1.2.2
│ │ ├── stringstream@0.0.5
│ │ ├── tough-cookie@2.2.1
│ │ └── tunnel-agent@0.4.2
│ ├─┬ request-progress@0.3.1
│ │ └── throttleit@0.0.2
│ └── which@1.0.9
├─┬ serve-static@1.10.0
│ ├── escape-html@1.0.2
│ └─┬ send@0.13.0
│   ├── depd@1.0.1
│   ├── destroy@1.0.3
│   ├── etag@1.7.0
│   ├── fresh@0.3.0
│   ├── http-errors@1.3.1
│   ├── mime@1.3.4
│   ├── range-parser@1.0.3
│   └── statuses@1.2.1
├─┬ tap-dot@1.0.1
│ ├─┬ tap-out@1.4.1
│ │ ├── re-emitter@1.1.1
│ │ ├── split@1.0.0
│ │ └── trim@0.0.1
│ └── through2@2.0.0
└─┬ tape@4.2.2
  ├── deep-equal@1.0.1
  ├── defined@1.0.0
  ├── function-bind@1.0.2
  ├── has@1.0.1
  ├── inherits@2.0.1
  ├── object-inspect@1.0.2
  ├── resumer@0.0.0
  ├─┬ string.prototype.trim@1.1.1
  │ ├─┬ define-properties@1.1.2
  │ │ ├── foreach@2.0.5
  │ │ └── object-keys@1.0.9
  │ └─┬ es-abstract@1.4.3
  │   ├─┬ es-to-primitive@1.0.0
  │   │ ├── is-date-object@1.0.1
  │   │ └── is-symbol@1.0.1
  │   ├── is-callable@1.1.1
  │   └── is-regex@1.0.3
  └── through@2.3.8


xxx@xxx /c/dev/test/pngjs (master)
$ npm test

> pngjs@2.2.0 test c:\dev\test\pngjs
> npm run lint && tape test/*-spec.js | tap-dot && node test/run-compare


> pngjs@2.2.0 lint c:\dev\test\pngjs
> eslint lib


c:\dev\test\pngjs\lib\bitpacker.js
  5:18  warning  Function 'anonymous' has a complexity of 14                        complexity
  5:18  warning  This function has too many statements (39). Maximum allowed is 30  max-statements

c:\dev\test\pngjs\lib\filter-pack.js
  20:1  warning  This function has too many parameters (6). Maximum allowed is 5  max-params
  71:1  warning  This function has too many parameters (6). Maximum allowed is 5  max-params
  98:1  warning  This function has too many parameters (6). Maximum allowed is 5  max-params

c:\dev\test\pngjs\lib\packer.js
  13:47  warning  Expected '!==' and instead saw '!='  eqeqeq
  14:53  warning  Expected '!==' and instead saw '!='  eqeqeq
  15:49  warning  Expected '!==' and instead saw '!='  eqeqeq

✖ 8 problems (0 errors, 8 warnings)


  ...............................................................................................................................................................................................................................................................................................................................................................................................................................................

  365 tests
  431 passed

  Pass!
Tests available at http://localhost:8000/
Comparing in PhantomJS
Comparison Test Results:
Success: f99n0g04, f04n2c08, f04n0g08, f03n2c08, f03n0g08, f02n2c08, f02n0g08, f01n2c08, f01n0g08, f00n2c08, f00n0g08, ctzn0g04, ctjn0g04, cthn0g04, ctgn0g04, ctfn0g04, cten0g04, ct1n0g04, ct0n0g04, cs8n3p08, cs8n2c08, cs5n3p08, cs5n2c08, cs3n3p08, cs3n2c16, cm9n0g04, cm7n0g04, cm0n0g04, ch2n3p08, ch1n3p04, cdun2c08, cdsn2c08, cdhn2c08, cdfn2c08, ccwn3p08, ccwn2c08, basn0g01, basn0g02, basn0g04, basn0g08, basn0g16, basn2c08, basn2c16, basn3p01, basn3p02, basn3p04, basn3p08, basn4a08, basn4a16, basn6a08, basn6a16, basi0g01, basi0g02, basi0g04, basi0g08, basi0g16, basi2c08, basi2c16, basi3p01, basi3p02, basi3p04, basi3p08, basi4a08, basi4a16, basi6a08, basi6a16, bgyn6a16, bgwn6a08, bggn4a16, bgbn4a08, bgan6a16, bgan6a08, bgai4a16, bgai4a08, z09n2c08, z06n2c08, z03n2c08, z00n2c08, tp1n3p08, tp0n3p08, tp0n2c08, tp0n0g08, tm3n3p02, tbyn3p08, tbwn3p08, tbwn0g16, tbrn2c08, tbgn3p08, tbgn2c16, tbbn3p08, tbbn2c16, tbbn0g04, s40n3p04, s40i3p04, s39n3p04, s39i3p04, s38n3p04, s38i3p04, s37n3p04, s37i3p04, s36n3p04, s36i3p04, s35n3p04, s35i3p04, s34n3p04, s34i3p04, s33n3p04, s33i3p04, s32n3p04, s32i3p04, s09n3p02, s09i3p02, s08n3p02, s08i3p02, s07n3p02, s07i3p02, s06n3p02, s06i3p02, s05n3p02, s05i3p02, s04n3p01, s04i3p01, s03n3p01, s03i3p01, s02n3p01, s02i3p01, s01n3p01, s01i3p01, ps2n2c16, ps2n0g08, ps1n2c16, ps1n0g08, pp0n6a08, pp0n2c16, oi9n2c16, oi9n0g16, oi4n2c16, oi4n0g16, oi2n2c16, oi2n0g16, oi1n2c16, oi1n0g16, g25n3p04, g25n2c08, g25n0g16, g10n3p04, g10n2c08, g10n0g16, g07n3p04, g07n2c08, g07n0g16, g05n3p04, g05n2c08, g05n0g16, g04n3p04, g04n2c08, g04n0g16, g03n3p04, g03n2c08, g03n0g16, gh-21
```

**Comment by lukeapage** [comment]
possibly your npm install failed somewhere?

**Comment by fuchsia** [comment]
I installed via npm:
```
E:\>mkdir \dev

E:\>cd dev

E:\dev>npm install pngjs
E:\dev
└── pngjs@2.2.0

npm WARN ENOENT ENOENT: no such file or directory, open 'E:\dev\package.json'
npm WARN EPACKAGEJSON dev No description
npm WARN EPACKAGEJSON dev No repository field.
npm WARN EPACKAGEJSON dev No README data
npm WARN EPACKAGEJSON dev No license field.

E:\dev>cd node_modules\pngjs

E:\dev\node_modules\pngjs>npm test

> pngjs@2.2.0 test E:\dev\node_modules\pngjs
> npm run lint && tape test/*-spec.js | tap-dot && node test/run-compare


> pngjs@2.2.0 lint E:\dev\node_modules\pngjs
> eslint lib


E:\dev\node_modules\pngjs\lib\bitpacker.js
  5:18  warning  Function 'anonymous' has a complexity of 14
    complexity
  5:18  warning  This function has too many statements (39). Maximum allowed is
30  max-statements

E:\dev\node_modules\pngjs\lib\filter-pack.js
  20:1  warning  This function has too many parameters (6). Maximum allowed is 5
  max-params
  71:1  warning  This function has too many parameters (6). Maximum allowed is 5
  max-params
  98:1  warning  This function has too many parameters (6). Maximum allowed is 5
  max-params

E:\dev\node_modules\pngjs\lib\packer.js
  13:47  warning  Expected '!==' and instead saw '!='  eqeqeq
  14:53  warning  Expected '!==' and instead saw '!='  eqeqeq
  15:49  warning  Expected '!==' and instead saw '!='  eqeqeq

✖ 8 problems (0 errors, 8 warnings)




  0 tests
  0 passed

  Pass!
module.js:329
    throw err;
    ^

Error: Cannot find module 'E:\dev\node_modules\pngjs\test\run-compare'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
npm ERR! Test failed.  See above for more details.
```
Have I done anything unreasonable? Is it something in the repo that's not in the distribution? pngjs itself works fine.

**Comment by lukeapage** [comment]
> Is it something in the repo that's not in the distribution

yes, tests are not distributed via npm. Its not normal to want to run the tests of a dependent module.

**Comment by fuchsia** [comment]
Then you probably want to amend your documentation to remind noobs of this. ;) (Or just remove the reference to testing.) Thanks.
