### ISSUE TITLE
Error installing version 2.3.0

### ISSUE THREAD

**Issue by oliver-moran** [lukeapage/pngjs#48]
Hi,

The latest of this package (2.3.0) doesn't install for me (and others). See here: https://github.com/oliver-moran/jimp/issues/129

The problem appears to be the addition of `node-zlib-backport`.

```
npm WARN engine node-zlib-backport@0.11.15: wanted: {"node":">=0.10 <0.11"} (cur
rent: {"node":"5.0.0","npm":"3.3.10"})

> node-zlib-backport@0.11.15 install C:\path\to\folder (2)\nod
e_modules\node-zlib-backport
> node-gyp rebuild


C:\path\to\folder (2)\node_modules\node-zlib-backport>if not d
efined npm_config_node_gyp (node "C:\path\to\folder\AppData\Roaming\npm\node_modu
les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  node_zlib.cc
C:\path\to\folder\.node-gyp\5.0.0\include\node\node_internals.h(5): fatal error
C1083: Cannot open include file: 'util.h': No such file or directory [C:\path\to\folder (2)\node_modules\node-zlib-backport\build\zlib.vcxpr
oj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\path\to\folder\AppData\Roaming\npm\
node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\path\\to\\folder\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\path\to\folder (2)\node_modules\node-zlib-back
port
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:node-zlib-backport@0.11.15 node-zlib-backport@0.11.15 install:
`node-gyp rebuild`
npm WARN install:node-zlib-backport@0.11.15 Exit status 1
C:\path\to\folder (2)
└── pngjs@2.3.0npm WARN engine node-zlib-backport@0.11.15: wanted: {"node":">=0.10 <0.11"} (cur
rent: {"node":"5.0.0","npm":"3.3.10"})

> node-zlib-backport@0.11.15 install C:\path\to\folder (2)\nod
e_modules\node-zlib-backport
> node-gyp rebuild


C:\path\to\folder (2)\node_modules\node-zlib-backport>if not d
efined npm_config_node_gyp (node "C:\path\to\folder\AppData\Roaming\npm\node_modu
les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  node_zlib.cc
C:\path\to\folder\.node-gyp\5.0.0\include\node\node_internals.h(5): fatal error
C1083: Cannot open include file: 'util.h': No such file or directory [C:\path\to\folder (2)\node_modules\node-zlib-backport\build\zlib.vcxpr
oj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\path\to\folder\AppData\Roaming\npm\
node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\path\\to\\folder\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\path\to\folder (2)\node_modules\node-zlib-back
port
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:node-zlib-backport@0.11.15 node-zlib-backport@0.11.15 install:
`node-gyp rebuild`
npm WARN install:node-zlib-backport@0.11.15 Exit status 1
C:\path\to\folder (2)
└── pngjs@2.3.0
```

**Comment by lukeapage** [comment]
I will fix it by removing the dependency and warning if on node 0.10 and it isnt installed. Should have time in the next 12 hours

**Comment by lukeapage** [comment]
2.3.1 released without dependency
