### ISSUE TITLE
node-zlib-backport doesn't build

### ISSUE THREAD

**Issue by efernandesng** [lukeapage/pngjs#49]
This issue is related with #47 

I get an error when I try `npm i pngjs`.

I think the problem only occurs with node 5, but I have not confirmed.

**Environment:**
- NodeJS v5.11.0
- node-gyp v3.3.1
- npm v3.8.7

```bash
[macgyver@arch project (master)]$ npm i pngjs

> node-zlib-backport@0.11.15 install /home/macgyver/dev/node/project/node_modules/node-zlib-backport
> node-gyp rebuild

make: Entering directory '/home/macgyver/dev/node/project/node_modules/node-zlib-backport/build'
  CXX(target) Release/obj.target/zlib/src/node_zlib.o
In file included from ../src/node_zlib.cc:32:0:
/home/macgyver/.node-gyp/5.11.0/include/node/node_internals.h:5:18: fatal error: util.h: No such file or directory
compilation terminated.
zlib.target.mk:86: recipe for target 'Release/obj.target/zlib/src/node_zlib.o' failed
make: *** [Release/obj.target/zlib/src/node_zlib.o] Error 1
make: Leaving directory '/home/macgyver/dev/node/project/node_modules/node-zlib-backport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.5.1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/macgyver/dev/node/project/node_modules/node-zlib-backport
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:node-zlib-backport@0.11.15 node-zlib-backport@0.11.15 install: `node-gyp rebuild`
npm WARN install:node-zlib-backport@0.11.15 Exit status 1
```

**Comment by efernandesng** [comment]
Sorry... I had not seen #48
