### ISSUE TITLE
Single pixel png causes "Ran out of data" error

### ISSUE THREAD

**Issue by pqvst** [lukeapage/pngjs#65]
When I try to load a 1x1 png I get the following error.

```
Error: Ran out of data
   at mapImage8Bit (\node_modules\pngjs\lib\bitmapper.js:109:17)
   at Object.exports.dataToBitMap (\node_modules\pngjs\lib\bitmapper.js:176:16)
   at ParserAsync._complete (\node_modules\pngjs\lib\parser-async.js:99:32)
   at emitOne (events.js:96:13)
   at emit (events.js:188:7)
   at _filter.Filter.complete (\node_modules\pngjs\lib\filter-parse-async.js:19:12)
   at Filter._reverseFilterLine (\node_modules\pngjs\lib\filter-parse.js:169:10)
   at ChunkStream._processRead (\node_modules\pngjs\lib\chunkstream.js:174:13)
   at ChunkStream._process (\node_modules\pngjs\lib\chunkstream.js:193:14)
   at ChunkStream.write (\node_modules\pngjs\lib\chunkstream.js:61:8)
```

I've attached the test image (it's hard to see but there is a 1x1 red pixel just below this text)

![test](https://cloud.githubusercontent.com/assets/4990657/19690636/9fbd4676-9ad1-11e6-8f5c-edc2bba57149.png)

**Comment by xtforgame** [comment]
The error threw by  [these lines](https://github.com/lukeapage/pngjs/blob/master/lib/bitmapper.js#L108..L110)
I don't know what is the original purpose, but maybe we don't need to check ```i === data.length``` here
Is it a typo of ```idx + rawPos === data.length``` ?

After remove these lines it works

**Comment by xtforgame** [comment]
This fix causes another error in the ```should correctly parse an 8-bit grayscale png``` test case, and I'm figuring out what is going on...

**Comment by xinxinw1** [comment]
Hi, I make a fix for this issue that doesn't break any existing test cases.

**Comment by lukeapage** [comment]
Fixed on master, will release later
