### ISSUE TITLE
Correct file is not parsed properly

### ISSUE THREAD

**Issue by toriningen** [lukeapage/pngjs#78]
I have discovered this problem when Appium refused to capture screenshots from Android device with weird internal error. I have investigated it a little, and it seems that Appium uses `jimp` to rotate screenshots to match device orientation, and `jimp` uses `pngjs` as codec, and `pngjs` refuses to load these files with following error:

    zlib.js:536
          throw error;
          ^
    
    Error: incorrect data check
        at Zlib._handle.onerror (zlib.js:355:17)
        at Inflate.Zlib._processChunk (zlib.js:526:30)
        at zlibBufferSync (zlib.js:225:17)
        at Object.exports.inflateSync (zlib.js:149:10)
        at module.exports (./pngjs/lib/parser-sync.js:69:27)
        at Object.exports.read (./pngjs/lib/png-sync.js:10:10)
        at Object.<anonymous> (./test.js:3:10)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)

I suppose that these files are valid, because PIL decodes them without problems, as well as do various browsers and desktop image viewers. These files were generated with following command sent via `adb shell`:

    $ /system/bin/screencap -p output.png

Device itself is Samsung Galaxy Note 4 (SM-N9100) running Android 5.0.1. I have created few sample files that are all "incorrect" according to pngjs, to maybe help you identify common details that prevent them from being properly parsed.

![screen1](https://cloud.githubusercontent.com/assets/14891625/24565422/d464c1e4-165d-11e7-8d35-943da60d45e9.png)
![screen2](https://cloud.githubusercontent.com/assets/14891625/24566283/934f8140-1661-11e7-8cad-cafc475b905f.png)
![screen3](https://cloud.githubusercontent.com/assets/14891625/24566282/9349fde2-1661-11e7-85ce-0dc621626a02.png)

Minimal code to parse these files is:

    var PNG = require('pngjs').PNG;
    
    PNG.sync.read(require('fs').readFileSync('output.png'));

**Comment by toriningen** [comment]
After a little more investigation it seems that all files I've provided have the sBIT chunk, [documented here](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.sBIT), which PIL just skips over. So, I guess, to make things work, you just need to skip over chunks you can't interpret.

**Comment by toriningen** [comment]
Problem is deeper than just having sBIT ignored, which you already do. Resulting IDAT payload is completely identical in PIL and pngjs, but I don't completely understand how does PIL unpack that. Investigating further.

**Comment by toriningen** [comment]
All the heavy lifting in PIL is seemingly done here - https://github.com/python-pillow/Pillow/blob/master/libImaging/ZipDecode.c#L44, so the problem is deeper, and might be not in pngjs, but in zlib itself. Looking for differences in control path when inflating valid PNG and sample PNG...

**Comment by toriningen** [comment]
Okay, I've tracked it down. It seems that `screencap` creates PNGs with little malformed zlib stream in IDAT chunks. It's not corrupted, but it's not properly teminated - so, decompression continues after bitmap has already ended and triggers zlib internal checks.

Then why does not this make PIL and other viewers fail? Because at least PIL decompesses PNGs row by row, and after decompessing the last row it just bails out, disregarding any extra data that may have left in IDAT, corrupt or not.

On C level it's done by setting `z_stream.avail_out` to the size of row = width * bits / 8 + 1 byte for row filter prefix. We are not required to decompress it row by row and could just extract whole image - it's `(width * bits / 8 + 1) * height` bytes. I don't know if there is a way to tell node.js to decompress in chunks yet. I will look into it.

There is also another solution, which seems hacky. It seems that if we manually strip out first 16 bits of IDAT chunk and tell zlib that it's raw and has windowBits of -15, then it just works. Produced stream has correct image in first `(width * bits / 8 + 1) * height` bytes. I don't know, however, whether it's safe to assume -15 for all unterminated PNG cases. Given they were always failing with obscure error before, it might be good try?

**Comment by toriningen** [comment]
Okay, I've got it working without using hacks, preparing pull request.
